### ISSUE TITLE
Update Guest.java - Match UML

### ISSUE THREAD

**Issue by Dierale** [Dierale/ZooGroup10#7]
The Guest.java class is effectively empty and requires the following functionalities to be implemented in order to match the UML diagram specifications.
 - public Guest()

JavaDoc comments should also be generated for the function described above.

File found at following location:
https://github.com/Dierale/ZooGroup10/blob/main/src/main/java/edu/nwmissouri/zoo10group/Guest.java

**Comment by Hemanthkumarreddy** [comment]
Updated guest class
